FROM python:3.7.4

# 仮想環境を /code/.venv に指定する
ENV PIPENV_VENV_IN_PROJECT 1

RUN mkdir /code/
ADD Pipfile /code/
ADD Pipfile.lock /code/
WORKDIR /code

RUN pip install --upgrade pip && \
  pip install pipenv && \
  pipenv --python /usr/local/bin/python

RUN pipenv install --dev && \
  apt-get update && \
  apt-get install -y mysql-client
